//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "HomeView.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string HomeView::genText(const DrTemplateData& HomeView_view_data)
{
	drogon::OStringStream HomeView_tmp_stream;
	std::string layoutName{""};
	HomeView_tmp_stream << "<!DOCTYPE html>\n";
	HomeView_tmp_stream << "<html lang=\"ar\" dir=\"rtl\">\n";
	HomeView_tmp_stream << "<head>\n";
	HomeView_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	HomeView_tmp_stream << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	HomeView_tmp_stream << "    <title>مشروع حمزة - C++ Backend</title>\n";
	HomeView_tmp_stream << "</head>\n";
	HomeView_tmp_stream << "<body>\n";
HomeView_tmp_stream<<"\n";
	HomeView_tmp_stream << "    <div class=\"card\">\n";
	HomeView_tmp_stream << "        ";
            auto userName = HomeView_view_data.get<std::string>("name");
            int solvedProblems = HomeView_view_data.get<int>("icpc_solved");
        
HomeView_tmp_stream<<"\n";
	HomeView_tmp_stream << "        <h1>🚀 مرحباً بك يا ";
{
    auto & val=HomeView_view_data["userName"];
    if(val.type()==typeid(const char *)){
        HomeView_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        HomeView_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	HomeView_tmp_stream << "!</h1>\n";
	HomeView_tmp_stream << "        <p>هذه الصفحة يتم عرضها باستخدام HTML و CSS، ولكنها مدعومة بالكامل بخادم <strong>C++</strong> فائق السرعة.</p>\n";
	HomeView_tmp_stream << "        \n";
	HomeView_tmp_stream << "        <p>عدد مسائل الخوارزميات التي قمت بحلها مؤخراً: <span class=\"highlight\">";
{
    auto & val=HomeView_view_data["solvedProblems"];
    if(val.type()==typeid(const char *)){
        HomeView_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        HomeView_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	HomeView_tmp_stream << "</span> مسألة.</p>\n";
	HomeView_tmp_stream << "        \n";
	HomeView_tmp_stream << "        <a href=\"#\" class=\"btn\">استكشف النظام</a>\n";
	HomeView_tmp_stream << "    </div>\n";
HomeView_tmp_stream<<"\n";
	HomeView_tmp_stream << "</body>\n";
	HomeView_tmp_stream << "    <style>\n";
	HomeView_tmp_stream << "        body {\n";
	HomeView_tmp_stream << "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n";
	HomeView_tmp_stream << "            background-color: #f0f2f5;\n";
	HomeView_tmp_stream << "            color: #333;\n";
	HomeView_tmp_stream << "            display: flex;\n";
	HomeView_tmp_stream << "            justify-content: center;\n";
	HomeView_tmp_stream << "            align-items: center;\n";
	HomeView_tmp_stream << "            height: 100vh;\n";
	HomeView_tmp_stream << "            margin: 0;\n";
	HomeView_tmp_stream << "        }\n";
	HomeView_tmp_stream << "        .card {\n";
	HomeView_tmp_stream << "            background: white;\n";
	HomeView_tmp_stream << "            padding: 40px;\n";
	HomeView_tmp_stream << "            border-radius: 12px;\n";
	HomeView_tmp_stream << "            box-shadow: 0 4px 15px rgba(0,0,0,0.1);\n";
	HomeView_tmp_stream << "            text-align: center;\n";
	HomeView_tmp_stream << "            max-width: 500px;\n";
	HomeView_tmp_stream << "        }\n";
	HomeView_tmp_stream << "        h1 {\n";
	HomeView_tmp_stream << "            color: #2b5797;\n";
	HomeView_tmp_stream << "            margin-bottom: 10px;\n";
	HomeView_tmp_stream << "        }\n";
	HomeView_tmp_stream << "        p {\n";
	HomeView_tmp_stream << "            font-size: 1.1em;\n";
	HomeView_tmp_stream << "            line-height: 1.6;\n";
	HomeView_tmp_stream << "        }\n";
	HomeView_tmp_stream << "        .highlight {\n";
	HomeView_tmp_stream << "            color: #e74c3c;\n";
	HomeView_tmp_stream << "            font-weight: bold;\n";
	HomeView_tmp_stream << "            font-size: 1.2em;\n";
	HomeView_tmp_stream << "        }\n";
	HomeView_tmp_stream << "        .btn {\n";
	HomeView_tmp_stream << "            display: inline-block;\n";
	HomeView_tmp_stream << "            margin-top: 20px;\n";
	HomeView_tmp_stream << "            padding: 10px 25px;\n";
	HomeView_tmp_stream << "            background-color: #2b5797;\n";
	HomeView_tmp_stream << "            color: white;\n";
	HomeView_tmp_stream << "            text-decoration: none;\n";
	HomeView_tmp_stream << "            border-radius: 6px;\n";
	HomeView_tmp_stream << "            transition: 0.3s;\n";
	HomeView_tmp_stream << "        }\n";
	HomeView_tmp_stream << "        .btn:hover {\n";
	HomeView_tmp_stream << "            background-color: #1e3f6e;\n";
	HomeView_tmp_stream << "        }\n";
	HomeView_tmp_stream << "    </style>\n";
	HomeView_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(HomeView_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = HomeView_view_data;
auto str = std::move(HomeView_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
