//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class LearnView:public drogon::DrTemplate<LearnView>
{
public:
	LearnView(){};
	virtual ~LearnView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
